- name: Setup Hosts
  hosts: all,!localhost
  roles:
  - basic_setup
  - diskpart
  tags:
  - setup

- name: Install FreeIPA server
  hosts: ipaserver
  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
  tags:
  - idm

- name: Install FreeIPA clients
  hosts: ipaclients
  roles:
  - role: freeipa.ansible_freeipa.ipaclient
    state: present
  tags:
  - idm_clients

- name: Install PostgreSQL Server
  hosts: postgres
  roles:
  - geerlingguy.postgresql
  tags:
  - postgres

- name: Install Gitlab Server
  hosts: gitlab_server
  roles:
  - cloudflare_acme
  - gitlab_server
  tags:
  - gitlab_server

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  tags:
  - k8s
