collections:
- name: https://github.com/kubernetes-sigs/kubespray
  type: git
  version: v2.24.0
- name: kubernetes.core
  version: 2.4.1
- name: community.general
  version: 8.3.0
- name: freeipa.ansible_freeipa
  version: 1.12.1
- name: community.sops
  version: 1.6.7
- name: community.crypto
  version: 2.18.0

roles:
- name: geerlingguy.postgresql
  version: 3.5.0
