- name: Install Domain Controller(s)
  hosts: ipaserver
  roles:
  - basic_setup
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
  tags:
  - idm

- name: Setup Hosts
  hosts: all,!localhost
  roles:
  - basic_setup
  - diskpart
  tags:
  - setup

- name: Install FreeIPA clients
  hosts: ipaclients
  roles:
  - role: freeipa.ansible_freeipa.ipaclient
    state: present
  tags:
  - idm_clients

- name: Install Gitlab Server
  hosts: gitlab_server
  roles:
  - cloudflare_acme
  - gitlab_server
  tags:
  - gitlab_server

- name: Install Hashicorp Vault Server
  hosts: hc_vault_server
  roles:
  - cloudflare_acme
  - hc_vault_server
  tags:
  - hc_vault_server

- name: Install Media Server
  hosts: media_server
  roles:
  - plex
  tags:
  - media_server
