---
# Gitlab Server
gitlab_domain: "gitlab.{{ local_domain }}"
gitlab_pages_domain: "pages.{{ local_domain }}"
gitlab_registry_domain: "registry.{{ local_domain }}"
gitlab_config_template: "{{ inventory_dir }}/templates/gitlab.rb"
gitlab_version: 16.*

gitlab_ldap_user: "{{ lookup('community.hashi_vault.hashi_vault', 'internal/data/gitlab_server:ldap_user') }}"
gitlab_ldap_password: "{{ lookup('community.hashi_vault.hashi_vault', 'internal/data/gitlab_server:ldap_password') }}"
gitlab_ldap_suffix: "{{ lookup('community.hashi_vault.hashi_vault', 'internal/data/gitlab_server:ldap_suffix') }}"

gitlab_root_data_dir: /mnt/gitlab/data
gitlab_backup_data_dir: /mnt/backups/gitlab

disks:
- device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
  mount_path: /mnt/gitlab
- device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
  mount_path: /mnt/backups

gitlab_keycloak_realm: ""
keycloak_domain: ""

acme_cert_domains:
- "{{ gitlab_domain }}"
- "{{ gitlab_pages_domain }}"
- "{{ gitlab_registry_domain }}"
acme_cloudflare_domain: "{{ public_domain }}"
acme_default_certificate_root_path: "/etc/gitlab/ssl"
