ipaserver_domain: "{{ local_domain | lower }}"
ipaserver_realm: "{{ local_domain | upper }}"
ipa_bind_domain_dc_components: "{{ ['dc='] | product(ipaserver_domain|split('.')) | map('join') | list }}"
