---
# file: basic_setup/tasks/debian.yml

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Disable install recommends
  ansible.builtin.copy:
    content: 'APT::Install-Recommends "0";'
    dest: /etc/apt/apt.conf.d/90recommends

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Install basic packages
  ansible.builtin.apt:
    pkg:
    - less
    - vim-nox
    - bash-completion
    - lsb-release
    - rsync
    - molly-guard
    - screen
    - tmux

- name: Set default locale to en_GB.UTF8
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: en_GB.UTF8
    vtype: select
