---
helm_enabled: true
registry_enabled: false
metrics_server_enabled: false
local_path_provisioner_enabled: false
local_volume_provisioner_enabled: false
cephfs_provisioner_enabled: false
rbd_provisioner_enabled: false
ingress_nginx_enabled: false
ingress_publish_status_address: ""
ingress_alb_enabled: false
cert_manager_enabled: false
metallb_enabled: false
metallb_speaker_enabled: "{{ metallb_enabled }}"
argocd_enabled: false
krew_enabled: false
krew_root_dir: "/usr/local/krew"

kube_vip_enabled: true
kube_vip_arp_enabled: true
kube_vip_controlplane_enabled: true
kube_vip_address: 10.0.0.100
# Defined in all/all.yml
# loadbalancer_apiserver:
#   address: "{{ kube_vip_address }}"
#   port: 6443
# Appears to be optional
# kube_vip_interface: bond0
kube_vip_services_enabled: false
