---
# tasks file for roles/hc_vault_server

- name: Run Debian specific Hashicorp Vault tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# - name: Ensure Hashicorp Vault directories exists
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: directory
#     owner: vault
#     group: vault
#     recurse: true
#   loop:
#   - "{{ hc_vault_config_dir }}"
#   - "{{ hc_vault_data_dir }}"

# - name: Template Hashicorp Vault Configuration file
#   ansible.builtin.template:
#     src: "{{ hc_vault_server_config_template }}"
#     dest: "{{ hc_vault_config_dir }}/config.hcl"
#     owner: vault
#     group: vault
#     mode: '0600'
#     backup: yes
