---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/sakura-dragon/clusters.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: common
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./common
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-base
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/main/infra-base
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  dependsOn:
    - name: common
